SELECT PRODUCTS.NAME, PROVIDERS.NAME, CATEGORIES.NAME
FROM PRODUCTS
JOIN PROVIDERS ON PRODUCTS.ID_PROVIDERS = PROVIDERS.ID
JOIN CATEGORIES ON PRODUCTS.ID_CATEGORIES = CATEGORIES.ID
WHERE PROVIDERS.NAME = 'Sansul SA' AND CATEGORIES.NAME = 'Imported';