SELECT PRODUCTS.NAME, PROVIDERS.NAME, PRODUCTS.PRICE
FROM PRODUCTS JOIN PROVIDERS ON PRODUCTS.ID_PROVIDERS = PROVIDERS.ID
JOIN CATEGORIES ON PRODUCTS.ID_CATEGORIES = CATEGORIES.ID
WHERE PRODUCTS.PRICE > 1000 AND CATEGORIES.NAME = 'Super Luxury';